### ISSUE TITLE
Error Qualified path resolution failed when trying to run `yarn watch`

### ISSUE THREAD

**Issue by mxro** [goldstack/goldstack-main#13]
When running `yarn watch` an `Error: Qualified path resolution failed - none of the candidates can be found on the disk.  ` is reported.

```
λ yarn watch
C:\Users\Max\Downloads\package\.pnp.js:21575
    throw firstError;
    ^

Error: Qualified path resolution failed - none of the candidates can be found on the disk.        

Source path: /C:/Users/Max/Downloads/package/packages/static-website-aws/dist/build.js
Rejected candidate: /C:/Users/Max/Downloads/package/packages/static-website-aws/dist/build.js     
Rejected candidate: /C:/Users/Max/Downloads/package/packages/static-website-aws/dist/build.js.js  
Rejected candidate: /C:/Users/Max/Downloads/package/packages/static-website-aws/dist/build.js.json
Rejected candidate: /C:/Users/Max/Downloads/package/packages/static-website-aws/dist/build.js.node

    at internalTools_makeError (C:\Users\Max\Downloads\package\.pnp.js:21322:34)
    at resolveUnqualified (C:\Users\Max\Downloads\package\.pnp.js:22314:13)
    at resolveRequest (C:\Users\Max\Downloads\package\.pnp.js:22338:14)
    at Object.resolveRequest (C:\Users\Max\Downloads\package\.pnp.js:22398:26)
    at Function.external_module_.Module._resolveFilename (C:\Users\Max\Downloads\package\.pnp.js:21552:34)
    at Function.external_module_.Module._load (C:\Users\Max\Downloads\package\.pnp.js:21418:51)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
    at internal/main/run_main_module.js:17:47
```

**Comment by mxro** [comment]
This is caused when `yarn build` or `yarn compile` have not been run for the project.

Simply run `yarn compile` and the command will succeed.
